Create generator for mocha.opts file
rcorp/standard-project-structure pull request #52
Opened 2016-10-11 12:40 UTC by riteshe63

Add mocha Framework to test cases.

2016-10-11 13:46 UTC, gaurav21r requested changes

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/templates/mocha.opts
> +
@riteshe63 Why so many extra spaces?

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/index.js
> +const yeoman = require('yeoman-generator');
@riteshe63 Is this file linted with eslint?

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/index.js
> +        'Add Testing Framework for test cases'
I think it would be better to say **Installing Testing frameworks**

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/index.js
> +        name: 'selectedFramework',
@riteshe63 Framework is too generic. It needs to `selectedTestFramework`.

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/index.js
> +   * Finally runs an npm install as well as installs plugins for editors.
@riteshe63 Irrelevent here as we are not installing anything for editors ATM.

2016-10-11 13:46 UTC, gaurav21r commented on generators/test/index.js
> +      this.log('Configuring Mocha for mocha test cases');
Should be *Configuring default options for mocha*

2016-10-11 13:51 UTC, gaurav21r requested changes
@riteshe63 Please ask @neerajsachan to submithis grunt file here.

2016-10-12 08:04 UTC, neerajsachan commented
Actually, presently  we are testing all unit test in the test/spec/unit/**/*.js file path in mocha-Test.  Can we use  test/unit/**/*.js path instead of the test/spec/unit/**/*.js path ? .

2016-10-12 09:37 UTC, riteshe63 commented
@gaurav21r  All Review is done, Please check.

2016-10-12 12:17 UTC, neerajsachan commented
Change path of the folder: generators/test/templates/grunt instead of generators/grunt .

2016-10-22 07:26 UTC, riteshe63 commented
@gaurav21r Please review code.

2016-10-25 12:45 UTC, merged